name: ia-cron-config
description: IA cron jobs
home: https://github.com/hmcts/ia-cron-config
apiVersion: v2
appVersion: "1.0"
version: 0.0.1
maintainers:
  - name: HMCTS IA Team
dependencies:
  - name: job
    version: 2.1.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
