name: ia-cron-config pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master
resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

jobs:
  - job: Validate
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: pia-cron-config
          chartReleaseName: ia-cron-config-ci-test
          chartNamespace: chart-tests

  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn: Validate
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: ia-cron-config
          chartReleaseName: ia-cron-config
          chartNamespace: chart-tests
